"""
training_script_builder.py
Generates a complete, runnable PyTorch training pipeline as a Python script string,
and also provides a TrainingConfig object for programmatic use.
"""

from dataclasses import dataclass, field
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Configuration dataclass
# ---------------------------------------------------------------------------

@dataclass
class TrainingConfig:
    # Optimiser
    optimizer: str = "adamw"          # sgd | adam | adamw
    learning_rate: float = 1e-3
    weight_decay: float = 1e-4
    momentum: float = 0.9             # SGD only

    # Scheduler
    scheduler: str = "cosine"         # step | cosine | onecycle | plateau
    epochs: int = 50
    warmup_epochs: int = 5

    # Data
    batch_size: int = 64
    num_workers: int = 4

    # Regularisation
    dropout_rate: float = 0.3
    label_smoothing: float = 0.0
    gradient_clip: float = 1.0
    use_mixed_precision: bool = True

    # Checkpointing
    checkpoint_dir: str = "checkpoints"
    early_stopping_patience: int = 10
    save_best_only: bool = True

    # Extra
    seed: int = 42
    log_interval: int = 10
    use_wandb: bool = False


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------

class TrainingScriptBuilder:
    """
    Derives a TrainingConfig from problem analysis and generates
    a ready-to-run Python training script as a string.
    """

    def build_config(self, spec: Any, analysis: Any) -> TrainingConfig:
        lr = self._pick_lr(analysis.arch_family)
        wd = 1e-2 if "weight_decay" in analysis.regularization else 1e-4
        epochs = self._pick_epochs(analysis.complexity_tier)
        patience = 15 if "early_stopping" in analysis.regularization else epochs
        ls = 0.1 if "label_smoothing" in analysis.regularization else 0.0

        return TrainingConfig(
            optimizer="adamw" if analysis.arch_family in ("transformer","resnet") else "adam",
            learning_rate=lr,
            weight_decay=wd,
            scheduler="cosine" if analysis.complexity_tier in ("medium","large") else "plateau",
            epochs=epochs,
            warmup_epochs=min(5, epochs // 10),
            batch_size=analysis.recommended_batch_size,
            dropout_rate=0.3 if "dropout" in analysis.regularization else 0.0,
            label_smoothing=ls,
            use_mixed_precision=analysis.use_mixed_precision,
            early_stopping_patience=patience,
        )

    def build_script(self, spec: Any, analysis: Any, arch_summary: Any) -> str:
        cfg = self.build_config(spec, analysis)
        loss_fn = self._pick_loss(spec)
        metric  = "accuracy" if spec.problem_type.lower() in ("classification","segmentation") else "mse"

        return f'''#!/usr/bin/env python3
"""
Auto-generated training script for {arch_summary.name}
Problem : {spec.problem_type}
Dataset : {spec.dataset_size:,} samples
Hardware: {spec.hardware}
Generated by neural-arch-gen
"""

import os, random
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, random_split
from torch.cuda.amp import GradScaler, autocast

# ── reproducibility ────────────────────────────────────────────────────────
SEED = {cfg.seed}
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
if torch.cuda.is_available(): torch.cuda.manual_seed_all(SEED)

# ── hyper-parameters ───────────────────────────────────────────────────────
CFG = dict(
    epochs              = {cfg.epochs},
    batch_size          = {cfg.batch_size},
    lr                  = {cfg.learning_rate},
    weight_decay        = {cfg.weight_decay},
    warmup_epochs       = {cfg.warmup_epochs},
    label_smoothing     = {cfg.label_smoothing},
    gradient_clip       = {cfg.gradient_clip},
    early_stop_patience = {cfg.early_stopping_patience},
    checkpoint_dir      = "{cfg.checkpoint_dir}",
    use_amp             = {cfg.use_mixed_precision} and torch.cuda.is_available(),
    log_interval        = {cfg.log_interval},
    num_workers         = {cfg.num_workers},
)

# ── device ─────────────────────────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {{device}}")

# ── model (import your generated model here) ───────────────────────────────
# from architecture_generator import ArchitectureGenerator
# from problem_analyzer import ProblemSpec, ProblemAnalyzer
# spec     = ProblemSpec(...)
# analysis = ProblemAnalyzer().analyze(spec)
# model, summary = ArchitectureGenerator().generate(spec, analysis)
# model = model.to(device)

# ── dataset (replace with your actual dataset) ─────────────────────────────
# from torchvision import datasets, transforms
# transform = transforms.Compose([transforms.ToTensor()])
# dataset   = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
# n_train   = int(0.9 * len(dataset))
# train_ds, val_ds = random_split(dataset, [n_train, len(dataset)-n_train])
# train_loader = DataLoader(train_ds, batch_size=CFG["batch_size"], shuffle=True,
#                           num_workers=CFG["num_workers"], pin_memory=True)
# val_loader   = DataLoader(val_ds,   batch_size=CFG["batch_size"]*2,
#                           num_workers=CFG["num_workers"], pin_memory=True)

# ── loss & optimiser ───────────────────────────────────────────────────────
criterion = {loss_fn}
optimizer = torch.optim.AdamW(model.parameters(), lr=CFG["lr"], weight_decay=CFG["weight_decay"])

# ── scheduler ──────────────────────────────────────────────────────────────
def build_scheduler(opt, cfg):
    warmup = torch.optim.lr_scheduler.LinearLR(opt, 1e-6/cfg["lr"], 1.0, total_iters=cfg["warmup_epochs"])
    cosine = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=cfg["epochs"]-cfg["warmup_epochs"])
    return torch.optim.lr_scheduler.SequentialLR(opt, [warmup, cosine], milestones=[cfg["warmup_epochs"]])

scheduler = build_scheduler(optimizer, CFG)
scaler    = GradScaler(enabled=CFG["use_amp"])

# ── training helpers ───────────────────────────────────────────────────────
os.makedirs(CFG["checkpoint_dir"], exist_ok=True)

def train_epoch(model, loader, criterion, optimizer, scaler, device, cfg):
    model.train(); total_loss = 0.0; correct = 0; total = 0
    for step, (X, y) in enumerate(loader):
        X, y = X.to(device), y.to(device)
        optimizer.zero_grad(set_to_none=True)
        with autocast(enabled=cfg["use_amp"]):
            preds = model(X)
            loss  = criterion(preds, y)
        scaler.scale(loss).backward()
        scaler.unscale_(optimizer)
        torch.nn.utils.clip_grad_norm_(model.parameters(), cfg["gradient_clip"])
        scaler.step(optimizer); scaler.update()
        total_loss += loss.item() * X.size(0)
        if preds.dim() > 1: correct += (preds.argmax(1) == y).sum().item()
        total += X.size(0)
        if step % cfg["log_interval"] == 0:
            print(f"  step {{step}}/{{len(loader)}}  loss={{loss.item():.4f}}")
    return total_loss/total, correct/total if total else 0

@torch.no_grad()
def evaluate(model, loader, criterion, device, cfg):
    model.eval(); total_loss = 0.0; correct = 0; total = 0
    for X, y in loader:
        X, y = X.to(device), y.to(device)
        with autocast(enabled=cfg["use_amp"]):
            preds = model(X); loss = criterion(preds, y)
        total_loss += loss.item() * X.size(0)
        if preds.dim() > 1: correct += (preds.argmax(1) == y).sum().item()
        total += X.size(0)
    return total_loss/total, correct/total if total else 0

# ── main training loop ─────────────────────────────────────────────────────
best_val_loss = float("inf"); patience_ctr = 0; history = []

for epoch in range(1, CFG["epochs"]+1):
    tr_loss, tr_acc = train_epoch(model, train_loader, criterion, optimizer, scaler, device, CFG)
    va_loss, va_acc = evaluate(model, val_loader, criterion, device, CFG)
    scheduler.step()
    lr_now = optimizer.param_groups[0]["lr"]
    history.append(dict(epoch=epoch, tr_loss=tr_loss, tr_acc=tr_acc, va_loss=va_loss, va_acc=va_acc))
    print(f"Epoch {{epoch:3d}}/{CFG['epochs']} | "
          f"train loss={{tr_loss:.4f}} acc={{tr_acc:.3f}} | "
          f"val loss={{va_loss:.4f}} acc={{va_acc:.3f}} | lr={{lr_now:.2e}}")

    # checkpoint
    if va_loss < best_val_loss:
        best_val_loss = va_loss; patience_ctr = 0
        path = os.path.join(CFG["checkpoint_dir"], "best_model.pt")
        torch.save(dict(epoch=epoch, model=model.state_dict(), optim=optimizer.state_dict(),
                        val_loss=va_loss), path)
        print(f"  Saved best checkpoint -> {{path}}")
    else:
        patience_ctr += 1
        if patience_ctr >= CFG["early_stop_patience"]:
            print(f"Early stopping at epoch {{epoch}}")
            break

print("Training complete.  Best val loss:", best_val_loss)
'''

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _pick_lr(family: str) -> float:
        return {"transformer": 5e-5, "resnet": 1e-4, "unet": 1e-4,
                "cnn": 1e-3, "mlp": 1e-3, "lstm": 1e-3, "tcn": 1e-3}.get(family, 1e-3)

    @staticmethod
    def _pick_epochs(tier: str) -> int:
        return {"tiny": 100, "small": 80, "medium": 60, "large": 40}.get(tier, 60)

    @staticmethod
    def _pick_loss(spec: Any) -> str:
        if spec.problem_type.lower() in ("classification", "nlp"):
            ls = 0.1 if spec.dataset_size > 10_000 else 0.0
            return f"nn.CrossEntropyLoss(label_smoothing={ls})"
        if spec.problem_type.lower() == "segmentation":
            return "nn.CrossEntropyLoss()"
        if spec.problem_type.lower() == "detection":
            return "nn.SmoothL1Loss()"
        return "nn.MSELoss()"


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    from problem_analyzer import ProblemSpec, ProblemAnalyzer
    from architecture_generator import ArchitectureGenerator

    spec     = ProblemSpec(problem_type="classification", dataset_size=8000,
                           num_classes=10, input_shape=(3,32,32), hardware="single_gpu")
    analysis = ProblemAnalyzer().analyze(spec)
    _, summary = ArchitectureGenerator().generate(spec, analysis)

    builder = TrainingScriptBuilder()
    cfg     = builder.build_config(spec, analysis)
    script  = builder.build_script(spec, analysis, summary)

    print("=== TrainingConfig ===")
    import json; print(json.dumps(cfg.__dict__, indent=2))
    print("\n=== Generated Script (first 30 lines) ===")
    print("\n".join(script.splitlines()[:30]))
